# -*- coding: utf-8 -*-
"""Assign-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ryFS3iDnxxmbnSLINLZtkeyLMQDghzI

1. In the below elements which of them are values or an expression? eg:- values can be
integer or string and expressions will be mathematical operators.
*
"hello"
-87.8
-
/
+
6

Ans:-  Values = "Hello"(string)
                 -87.8
                  6
       Expressions = *,-,/,+

2. What is the difference between string and variable?

Ans:-The difference between string and variable is:

* Variables are symbols that you can use to store data in a program. You can think of them as an empty box that you fill with some data or value. 

* Strings are data, so we can use them to fill up a variable. Declaring strings as variables can make it easier for us to work with strings throughout our Python programs.

3. Describe three different data types.

Ans:- Integers, floating-point numbers, and strings.

* Python Numeric Data Type:- Python numeric data type is used to hold numeric values like 1,2,3,4

* Python String Data Type. The string is a sequence of characters. ..."Hello world", "iNeuron"

* Python List Data Type. The list is a versatile data type exclusive in Python. ...List = []

* Python Tuple. ... Ex:-()

* Python Dictionary. Ex:-{}

4. What is an expression made up of? What do all expressions do?

Ans:- A combination of operands and operators is called an expression. The expression in Python produces some value or result after being interpreted by the Python interpreter. An expression in Python is a combination of operators and operands.

5. This assignment statements, like spam = 10. What is the difference between an
expression and a statement?

Ans:- An expression evaluates to a single value. But a  statement does not.

6. After running the following code, what does the variable bacon contain?
bacon = 22
bacon + 1

Ans:- 
        The bacon variable is set to 20. The bacon + 1 expression does not reassign the value in bacon (that would need an assignment statement: bacon = bacon + 1)

7. What should the values of the following two terms be?

'spam' + 'spamspam'

'spam*3
"""

'spam'+'spamspam'
'spam'*3
#Both expressions evaluate to the string 'spamspamspam'

"""8. Why is eggs a valid variable name while 100 is invalid?

Ans:- Eggs is variable name because it starts with an alphabet
  
  while 100 is a numeric value and Variable names cannot begin with a number.

9. What three functions can be used to get the integer, floating-point number, or string
version of a value?

Ans:- The int(), float(), and str() functions will evaluate to the integer, floating-point number, and string versions of the value passed to them.

10. Why does this expression cause an error? How can you fix it?
'I have eaten'+99+'burritos.'

Ans:- 

The expression causes an error because 99 is an integer, and only strings can be concatenated to other strings with the + operator. The correct way is I have eaten ' + str(99) + ' burritos.'.
"""